### ISSUE TITLE
Update sponsored and staging buckets to use `dandiset_bucket` module

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-infrastructure#107]
I added a new `dandiset_bucket` module and used it to concisely define the embargo buckets. It should also be used to define the non-embargo buckets as well. It will involve manipulating Terraform state to get it to forget the old bucket definitions and become aware that the new definitions are already present.

**Comment by brianhelba** [comment]
FYI, the latest version of TF has the `moved` block, which may help here: https://learn.hashicorp.com/tutorials/terraform/move-config#move-your-resources-with-the-moved-configuration-block

**Comment by waxlamp** [comment]
@AlmightyYakob, @mvandenburgh: does #121 close this issue? It has been a few months since the PR was approved, so I want to make sure it's still an appropriate solution.

**Comment by mvandenburgh** [comment]
#121 doesn't solve this. The goal of this issue is to refactor the Terraform code for the public s3 buckets to use the `dandiset_bucket` module that the embargoed buckets currently use, instead of duplicating the code.

#121 encodes a change that was already made to s3 into Terraform, and should be merged ASAP.
