### ISSUE TITLE
Cross-platform DANDI app

### ISSUE THREAD

**Issue by satra** [dandi/dandi-infrastructure#4]
electron-based app

- [ ] build and deploy via Travis
- [ ] upload
- [ ] validate

**Comment by yarikoptic** [comment]
do you see anyone working on this issue or for now we better close it as a wontfix, @satra ?

**Comment by satra** [comment]
not immediately.

**Comment by waxlamp** [comment]
This is off of our collective radar at the moment, and there's no need to track in an issue because if and when we want an electron app, we'll need to create a host of issues to track the work in any case. Besides all that, I don't think this is the right repo for this issue anyway: this repo is all about our IaC materials for our staging and production deploys of DANDI.

I vote to close.
